import { MemWal, RecallResult } from '@mysten-incubation/memwal';
import { ns, UserContext } from './namespaces.js';
import { WorkflowNode, RecallMemory } from '@m2a/sdk';

export class MemoryRouter {
  constructor(
    private poolClient: MemWal,
    private getUserClient: (delegateKey: string, accountId: string) => MemWal
  ) { }

  /**
   * Recalls memories for a specific execution node, pulling from all required namespaces.
   */
  async recallForNode(
    node: WorkflowNode,
    query: string,
    userContext: UserContext & { delegateKey: string; accountId: string }
  ): Promise<RecallMemory[]> {
    const results: RecallMemory[] = [];

    if (node.type !== 'agent' || !node.memory_tier || !node.memory_tier.read) {
      return results;
    }

    for (const namespaceTemplate of node.memory_tier.read) {
      const namespace = ns.resolve(namespaceTemplate, userContext);

      const r: RecallResult = await (namespace.startsWith('pool::') 
        ? this.poolClient.recall(query, undefined, namespace)
        : this.getUserClient(userContext.delegateKey, userContext.accountId).recall(query, undefined, namespace));

      const mapped: RecallMemory[] = r.results.map((res: any) => ({
        namespace,
        content: res.content,
        timestamp: res.metadata?.timestamp || Date.now(),
        distance: res.distance
      }));

      results.push(...mapped);
    }

    // Deduplicate by content and sort by distance
    const sorted = results.sort((a, b) => (a.distance || 0) - (b.distance || 0));
    
    // Return unique content to save context window space
    const unique = new Set<string>();
    return sorted.filter(r => {
      if (unique.has(r.content)) return false;
      unique.add(r.content);
      return true;
    });
  }

  /**
   * Commits memories generated by a node to the configured write namespaces.
   * Runs asynchronously (fire and forget) to prevent blocking execution.
   */
  async rememberFromNode(
    node: WorkflowNode,
    text: string,
    userContext: UserContext & { delegateKey: string; accountId: string }
  ): Promise<void> {
    if (node.type !== 'agent' || !node.memory_tier || !node.memory_tier.write) {
      return;
    }

    for (const namespaceTemplate of node.memory_tier.write) {
      const namespace = ns.resolve(namespaceTemplate, userContext);

      if (namespace.startsWith('pool::')) {
        this.poolClient.remember(text, namespace).catch(console.error);
      } else {
        const userClient = this.getUserClient(userContext.delegateKey, userContext.accountId);
        userClient.remember(text, namespace).catch(console.error);
      }
    }
  }
}
